plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace "com.naufalpratomo.musicgit"
    compileSdk 34

    defaultConfig {
        applicationId "com.naufalpratomo.musicgit"
        minSdk 24
        targetSdk 34
        versionCode 220
        versionName "2.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86_64"
        }

        python {
            version "3.11"
            pip {
                install "yt-dlp"
                install "mutagen"
                install "httpx"
                install "requests"
                install "pillow"
                install "fastapi<0.100.0"
                install "pydantic<2.0"
                install "uvicorn"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.media:media:1.7.0'
}

task syncPythonBackend(type: Copy) {
    from "${rootDir}/../backend"
    into "${projectDir}/src/main/python/backend"
}

task syncFrontendAssets(type: Copy) {
    from "${rootDir}/../frontend"
    into "${projectDir}/src/main/python/frontend"
}

tasks.matching { it.name.startsWith("merge") || it.name.startsWith("generate") || it.name.startsWith("process") || it.name.startsWith("compile") }.configureEach {
    dependsOn syncPythonBackend, syncFrontendAssets
}

